### ISSUE TITLE
Clean frontmatter after migrating to website

### ISSUE THREAD

**Issue by kelvindecosta** [acmbpdc/openlib.cs#7]
## Clean frontmatter after migrating to website

So, my script definitely achieved its goal of reducing the amount of manual text manipulation.
However, it could only do so much and hence the frontmatter of each course needs to be cleaned

## Step 0 - Guidelines

*   When making a commit, refer to this issue.
    ```bash
    git commit -m "Update <course_code> based on #<issue_no>"
    ```
    By doing this, all commits related to changing the frontmatter will be displayed alongside this issue on GitHub.
    Do not accidentally close this issue by doing [this](https://help.github.com/en/articles/closing-issues-using-keywords)

*   Stick to the order of attributes shown in the above convention.
    This will improve the efficiency of maintaining the library

*   Avoid typos, especially those on proper nouns.
    After making a change on your local repository, run the local server and take a look at your change.
    If things look good commit and push

*   There may be junk characters in the strings that need to be removed.
    This is due to the inefficiency of the previous method of maintaining the library

*   If necessary, alter the `title` of a resource so that it makes sense to a user who might not be familiar with the `author`

*   The `author` of a learning resource can be an individual or an organization 
    If the `author` of a learning resource is truly anonymous, that attribute should be left blank.

*   Support for viewing `remarks` is not yet implemented. If you need to further explain a resource add this attribute.

*   `Prerequisites` are dead. For now.

## Step 1 - Code & Title

Ensure that each course has its appropriate `code` & `title` in the frontmatter

```yaml
code: CSF111
title: Computer Programming
```

## Step 2 - Textbooks

Ensure that the frontmatter array `textbooks` has these attributes

```python
["title", "author", "edition", "year", "url"]
```

```yaml
textbooks:
-   title: The C Programming Language
    author: Brian Kernighan & Dennis Ritchie
    edition: 2nd
    year: '1989'
    url: https://drive.google.com/open?id=1KH0i1C8IQ5uKO4zGWRz_mAh4XbQvCaiT
-   title: The C Answer Book
    author: Clovis L. Tondo & Scott E. Gimpel
    edition: 2nd
    year: '1989'
    url: https://drive.google.com/open?id=1gfgZmONMV6ZcG-lIQOe35jiMVqI-MS3p
```

## Step 3 - Source Code

Ensure that the frontmatter array `source-code` has these attributes

```python
["title", "author", "url"]
```

Here, `author` is the username of the author on the respective site

```yaml
source-code:
-   title: 'CPrograms'
    author: eash-98
    url: https://github.com/eash-98/CPrograms
```

## Step 4 - Videos

Ensure that the frontmatter array `videos` has these attributes

```python
["title", "author", "url"]
```

Refer to either single videos or entire playlists

```yaml
videos:
-   title: 'C Programming & Data Structures'
    author: Neso Academy
    url: https://www.youtube.com/watch?v=4OGMB4Fhh50&list=PLBlnK6fEyqRhX6r2uhhlubuF5QextdCSM
-   title: 'CS50: Introduction to Computer Science'
    author: Harvard
    url: https://www.youtube.com/watch?v=wEdvGqxafq8
```

## Step 5 - Websites

Ensure that the frontmatter array `websites` has these attributes

```python
["title", "author", "url"]
```

This section is meant for any webpage or website that may benefit the user

```yaml
websites:
-   title: 'Algorithms'
    author: HackerRank
    url: https://www.hackerrank.com/domains/algorithms
-   title: 'Bandit'
    author: OverTheWire
    url: http://overthewire.org/wargames/bandit/
```

## Step 6 - Articles

Ensure that the frontmatter array `articles` has these attributes

```python
["title", "author", "url"]
```

```yaml
articles:
-   title: 'Using vi, the Unix Visual Editor'
    author: University of Washington
    url: https://staff.washington.edu/rells/R110/
```

## Step 7 - Communities

Ensure that the frontmatter array `communities` has these attributes

```python
["title", "url"]
```

```yaml
communities:
-   title: r/programming
    url: https://www.reddit.com/r/programming/
-   title: GeeksforGeeks
    url: https://www.geeksforgeeks.org/c-programming-language/
```

## Step 8 - Apps

Ensure that the frontmatter array `apps` has these attributes

```python
["title", "author", "url"]
```

The `url` should not discriminate between users of different mobile operating systems.
Link to the app's website download page to facilitate both users

```yaml
apps:
-   title: 'Py: Learn on the Go'
    author: 'Py'
    url: https://www.getpy.com/mobile
```
